"""Add Patient and Examination

Revision ID: 035818e17592
Revises: 5b061930f846
Create Date: 2026-07-17 04:26:57.825166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035818e17592'
down_revision = '5b061930f846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('patient_code', sa.String(length=30), nullable=False),
    sa.Column('created_by_doctor', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_doctor'], ['doctor_profiles.doctor_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('patient_code')
    )
    op.create_table('examinations',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('chief_complaint', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.doctor_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('exam_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examinations')
    op.drop_table('patients')
    # ### end Alembic commands ###
