"""Create medical workflow tables

Revision ID: 2bb53b3269c9
Revises: 651ab66332fb
Create Date: 2026-07-17 04:36:57.046218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb53b3269c9'
down_revision = '651ab66332fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target_table', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('consent_records',
    sa.Column('consent_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['examinations.exam_id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['doctor_profiles.doctor_id'], ),
    sa.PrimaryKeyConstraint('consent_id')
    )
    op.create_table('doctor_reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.doctor_id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['examinations.exam_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('report_prediction_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['ai_predictions.prediction_id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['doctor_reports.report_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_prediction_refs')
    op.drop_table('doctor_reports')
    op.drop_table('consent_records')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
