"""update benh table

Revision ID: 4b39037f4d31
Revises: 6dbb8ba9c3c6
Create Date: 2026-07-21 22:33:23.180983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b39037f4d31'
down_revision = '6dbb8ba9c3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('risk_factors', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('follow_up', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('common_locations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('age_group', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('gender_prevalence', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('prevalence', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('icd10_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_column('icd10_code')
        batch_op.drop_column('prevalence')
        batch_op.drop_column('gender_prevalence')
        batch_op.drop_column('age_group')
        batch_op.drop_column('common_locations')
        batch_op.drop_column('follow_up')
        batch_op.drop_column('risk_factors')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
