"""add diseases table

Revision ID: 718e7ce03f0d
Revises: 2bb53b3269c9
Create Date: 2026-07-21 22:13:52.536353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718e7ce03f0d'
down_revision = '2bb53b3269c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diseases',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('disease_code', sa.String(length=20), nullable=False),
    sa.Column('disease_name', sa.String(length=100), nullable=False),
    sa.Column('disease_name_vi', sa.String(length=100), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('causes', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prevention', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('reference_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('disease_id'),
    sa.UniqueConstraint('disease_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diseases')
    # ### end Alembic commands ###
