"""Create lesion image and metadata tables

Revision ID: d6c8d1eb2b08
Revises: 035818e17592
Create Date: 2026-07-17 04:32:53.329574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c8d1eb2b08'
down_revision = '035818e17592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesion_images',
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('crop_path', sa.String(length=255), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['examinations.exam_id'], ),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('image_metadata',
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('lesion_location', sa.String(length=100), nullable=True),
    sa.Column('skin_type', sa.String(length=50), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['lesion_images.image_id'], ),
    sa.PrimaryKeyConstraint('metadata_id'),
    sa.UniqueConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_metadata')
    op.drop_table('lesion_images')
    # ### end Alembic commands ###
