from .user import User
from .doctor_profile import DoctorProfile
from .patient import Patient
from .examination import Examination
from .lesion_image import LesionImage
from .image_metadata import ImageMetadata
from .ai_prediction import AIPrediction
from .ai_prediction_detail import AIPredictionDetail
from .ai_heatmap import AIHeatmap
from .doctor_report import DoctorReport
from .report_prediction_ref import ReportPredictionRef
from .consent_record import ConsentRecord
from .audit_log import AuditLog